server {
    listen 80;
    listen [::]:80;

    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;

    client_max_body_size 64M;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    location ~ \.php$ {
        try_files $uri =404;

        # app:9000 = 127.0.0.1
        fastcgi_pass 127.0.0.1:9000;

        # Use for local development
          fastcgi_pass 127.0.0.1:9000;

        # use for docker-compose
        # fastcgi_pass app:9000;

        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        # Vercel -> Nginx -> PHP-FPM
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;

        # Tell PHP/Laravel the original request was HTTPS
        fastcgi_param HTTPS on;

        fastcgi_hide_header X-Powered-By;

        fastcgi_read_timeout 300;

        fastcgi_buffer_size 32k;
        fastcgi_buffers 16 16k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2)$ {
        try_files $uri =404;

        expires 30d;
        access_log off;

        add_header Cache-Control "public, no-transform" always;
    }
}
